compress_assets: off
gzip_assets: off

javascripts:
  foundation:
    - javascripts/jquery-1.5.1.min.js
    - javascripts/jquery.reveal.js
    - javascripts/jquery.orbit-1.3.0.js
    - javascripts/forms.jquery.js
    - javascripts/jquery.customforms.js
    - javascripts/jquery.placeholder.min.js